✨ (viewer) Hide logs until end of turn.
boardgamers/gaia-project pull request #92
Opened 2021-04-28 03:14 UTC by RobertBolender

Hello! I have recently started playing this game *seriously* thanks to this project, and I am extremely thankful 🙇 

My personal favorite workflow is to keep the log placement on "top" with the log set to "recent", so that I can review what has changed since I made my last move. Then I prefer to hide the log while I scroll back and forth from the game board and my player board, which I frequently do on mobile. Adding an explicit option to hide the logs *for now* without having to open the preferences sidebar will make this workflow much easier.

I work professionally with React and haven't touched Vue in a while, please let me know if I can make this any more idiomatic or better fit in with the existing code style. Or if you have no interest in supporting this feature, I also would totally understand 😃

2021-04-28 03:53 UTC, zeitlinger commented
Great,  I like the idea 😀

I'm playing in a similar way. 
Looking forward to more contributions like this!

2021-04-28 03:54 UTC, zeitlinger commented on viewer/src/components/Game.vue
> +      this.toggledLog = false;
I think hideLog would be easier to understand

2021-04-29 07:29 UTC, coyotte508 requested changes
Really sorry - I left this review pending overnight, forgot to click "submit review" on github

2021-04-29 16:22 UTC, RobertBolender commented on viewer/src/components/Game.vue
> +      @toggleLog="handleToggleLog"
Nifty! Updated 👍

2021-04-29 16:25 UTC, RobertBolender commented on viewer/src/components/Game.vue
> +      @toggleLog="handleToggleLog"
Of note: this syntax changed in Vue 3:
https://v3.vuejs.org/guide/migration/v-model.html#using-v-bind-sync

2021-04-29 16:33 UTC, merged

2021-04-29 16:34 UTC, coyotte508 commented on viewer/src/components/Game.vue
> +      @toggleLog="handleToggleLog"
Yeah - vue3 would probably be a big rewrite